# Generated by Django 2.1.4 on 2018-12-25 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_type', models.CharField(choices=[('P', 'Pawn'), ('R', 'Rook'), ('K', 'Knight'), ('B', 'Bishop'), ('Q', 'Queen'), ('K', 'King')], max_length=1)),
                ('team', models.CharField(choices=[('B', 'Black'), ('W', 'White')], max_length=1)),
                ('chess_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess.ChessMatch')),
            ],
        ),
    ]
