# Generated by Django 2.1.4 on 2018-12-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_chesspiece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesspiece',
            name='piece_type',
            field=models.CharField(choices=[('P', 'Pawn'), ('R', 'Rook'), ('KN', 'Knight'), ('B', 'Bishop'), ('Q', 'Queen'), ('KI', 'King')], max_length=2),
        ),
    ]
