# Generated by Django 2.1.4 on 2018-12-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0003_auto_20181225_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesspiece',
            name='column',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chesspiece',
            name='move_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chesspiece',
            name='row',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
