# Generated by Django 2.1.4 on 2018-12-26 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0005_auto_20181226_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chesspiece',
            name='can_castle',
        ),
        migrations.RemoveField(
            model_name='chesspiece',
            name='can_double_jump',
        ),
    ]
