# Generated by Django 2.1.4 on 2018-12-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0006_auto_20181226_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chesspiece',
            name='column',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='chesspiece',
            name='row',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
