# Generated by Django 2.1.4 on 2019-07-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0007_auto_20181226_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesspiece',
            name='captured',
            field=models.BooleanField(default=False),
        ),
    ]
